annotations:
  category: Database
apiVersion: v2
appVersion: 10.5.8
dependencies:
  - name: common
    repository: https://svtechnmaa.github.io/charts/artifacthub/
    version: 1.x.x
description: MariaDB Galera is a multi-master database cluster solution for synchronous replication and high availability.
engine: gotpl
name: mariadb-galera
version: 5.6.8
