annotations:
  category: Database
apiVersion: v2
appVersion: 2.0.6
dependencies:
  - name: common
    repository: https://moophat.github.io/SVTECH_Public_Helmchart/artifacthub/
    version: 1.x.x
description: InfluxDB(TM) is an open source time-series database designed to handle large write and read loads in real-time.
engine: gotpl
keywords:
  - influxdb
  - tick
  - database
  - timeseries
name: influxdb
version: 2.2.2
