---
{{- $ns := .Release.Namespace }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: {{ $ns }}-ingress-nginx
    app.kubernetes.io/part-of: {{ $ns }}-ingress-nginx
data:
{{- range .Values.service.portBackend }}
{{- if eq .protocol "TCP" }}
  {{ .port }}: "{{ $ns }}/{{ .name }}:{{ .targetPort }}"
{{- end }}
{{- end }}
