apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /{{ .Chart.Name }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.global.elasticsearch.clusterName }}-kb-http
            port:
              number: 5601